controller_manager:
  ros__parameters:
    update_rate: 100

    # Controller types
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_action_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Controller parameters
arm_controller:
  ros__parameters:
    joints:
      - S1
      - S2
      - S3
      - E1
      - E2
      - W1
      - W2
      - finger_1_joint
      - finger_2_joint


    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true

gripper_action_controller:
  ros__parameters:
    joint: gripper_controller
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 100.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
